"""empty message

Revision ID: 2d95b39a377d
Revises: 848159077af3
Create Date: 2024-12-16 12:06:22.812022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d95b39a377d'
down_revision = '848159077af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('types', sa.String(length=80), nullable=False))
        batch_op.alter_column('planets',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('planets',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('types')

    # ### end Alembic commands ###
