"""empty message

Revision ID: 848159077af3
Revises: dc9669d0c96f
Create Date: 2024-12-16 11:53:39.618916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848159077af3'
down_revision = 'dc9669d0c96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(length=80), nullable=False),
    sa.Column('specie', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planets', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
